app = "echo-bot"

kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "iad"

[build]
  builder = "heroku/buildpacks:20"

# [deploy]
#   release_command = "sh /usr/src/app/scripts/release.sh"

[env]
  BOT_TOKEN = "$BOT_TOKEN"
  CLIENT_ID = "$CLIENT_ID"
  PRIMARY_REGION = "iad"
  NODE_ENV = "production"

[experimental]
  allowed_public_ports = []
  auto_rollback = true